server {
    listen 80;
    server_name tu.subdominio.com; # Cambia esto a tu subdominio
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name tu.subdominio.com; # Cambia esto a tu subdominio

    ssl_certificate /etc/nginx/certs/cloudflare.crt;
    ssl_certificate_key /etc/nginx/certs/cloudflare.key;

    ssl_session_cache shared:SSL:1m;
    ssl_session_timeout 5m;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    root /usr/share/nginx/html;
    index index.html index.htm;
    
    include /etc/nginx/conf.d/cloudflare.conf;

    location / {
        try_files $uri $uri/ =404;
    }
}